In [7]:
# unique method
import pandas as pd
import numpy as np
data={
    'Name':["Ali","Moussa","Jacob","Marie","Celine","Joseph","Mariam"],
    'Age':[29,30,23,26,23,20,20],
    'interst':["cooking","reading","dancing","playing","singing","meditation","swimming"]
}
df=pd.DataFrame(data)
print(df)
print()
print(df.Age.unique())
print()
print(df.Age.mean())

     Name  Age     interst
0     Ali   29     cooking
1  Moussa   30     reading
2   Jacob   23     dancing
3   Marie   26     playing
4  Celine   23     singing
5  Joseph   20  meditation
6  Mariam   20    swimming

[29 30 23 26 20]

24.428571428571427

In [8]:
df.head(2)

     Name  Age  interst
0     Ali   29  cooking
1  Moussa   30  reading

In [10]:
df.tail(3)

     Name  Age     interst
4  Celine   23     singing
5  Joseph   20  meditation
6  Mariam   20    swimming

In [13]:
df.dtypes

Name       object
Age         int64
interst    object
dtype: object